///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
// ignore_for_file: non_constant_identifier_names

class ilceler {
/*
{
  "IlceAdi": "ARNAVUTKOY",
  "IlceAdiEn": "ARNAVUTKOY",
  "IlceID": "9535"
} 
*/

  String? IlceAdi;
  String? IlceAdiEn;
  String? IlceID;

  ilceler({
    this.IlceAdi,
    this.IlceAdiEn,
    this.IlceID,
  });
  ilceler.fromJson(Map<String, dynamic> json) {
    IlceAdi = json['IlceAdi']?.toString();
    IlceAdiEn = json['IlceAdiEn']?.toString();
    IlceID = json['IlceID']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['IlceAdi'] = IlceAdi;
    data['IlceAdiEn'] = IlceAdiEn;
    data['IlceID'] = IlceID;
    return data;
  }
}
