///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
// ignore_for_file: non_constant_identifier_names

class Ulkeler {
/*
{
  "UlkeAdi": "ABD",
  "UlkeAdiEn": "USA",
  "UlkeID": "33"
} 
*/

  String? UlkeAdi;
  String? UlkeAdiEn;
  String? UlkeID;

  Ulkeler({
    this.UlkeAdi,
    this.UlkeAdiEn,
    this.UlkeID,
  });
  Ulkeler.fromJson(Map<String, dynamic> json) {
    UlkeAdi = json['UlkeAdi']?.toString();
    UlkeAdiEn = json['UlkeAdiEn']?.toString();
    UlkeID = json['UlkeID']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['UlkeAdi'] = UlkeAdi;
    data['UlkeAdiEn'] = UlkeAdiEn;
    data['UlkeID'] = UlkeID;
    return data;
  }
}
